export const vocabularyData = [
  {
    id: 'people',
    title: 'Люди',
    icon: '👨‍👩‍👧',
    level: 'A1',
    totalWords: 198,
    subcategories: [
      { title: 'Тіло', icon: '🦵', level: 'A1', words: 21 },
      { title: 'Обличчя', icon: '👁️', level: 'A2', words: 31 },
      { title: 'Кисті та стопи', icon: '🦶', level: 'B1', words: 10 },
      { title: 'М\'язи та скелет', icon: '💀', level: 'B2', words: 12 },
      { title: 'Органи', icon: '🫀', level: 'B2', words: 11 },
      { title: 'Сім\'я', icon: '🏠', level: 'A1', words: 31 },
      { title: 'Почуття', icon: '❤️', level: 'A1', words: 19 },
      { title: 'Життєві події', icon: '💍', level: 'B1', words: 29 },
      { title: 'Розпорядок дня', icon: '⏰', level: 'A2', words: 9 },
      { title: 'Риси характеру', icon: '🎭', level: 'B1', words: 25 },
    ]
  },
  {
    id: 'appearance',
    title: 'Зовнішність',
    icon: '👕',
    level: 'A1',
    totalWords: 37,
    subcategories: [
      { title: 'Зовнішність', icon: '💇', level: 'A2', words: 11 },
      { title: 'Одяг', icon: '👗', level: 'A1', words: 26 },
    ]
  },
  {
    id: 'health',
    title: 'Здоров\'я',
    icon: '🏥',
    level: 'A2',
    totalWords: 68,
    subcategories: [
      { title: 'Хвороба', icon: '🤒', level: 'B1', words: 17 },
      { title: 'У лікаря', icon: '👨‍⚕️', level: 'A2', words: 17 },
      { title: 'Лікарня', icon: '🚑', level: 'B1', words: 11 },
      { title: 'Стоматолог', icon: '🦷', level: 'B1', words: 8 },
      { title: 'Оптика', icon: '👓', level: 'B2', words: 5 },
      { title: 'Харчування', icon: '🥗', level: 'B1', words: 10 },
    ]
  },
  {
    id: 'home',
    title: 'Дім',
    icon: '🏠',
    level: 'A1',
    totalWords: 219,
    subcategories: [
      { title: 'Район', icon: '🏘️', level: 'B1', words: 15 },
      { title: 'Вітальня', icon: '🛋️', level: 'A2', words: 14 },
      { title: 'Їдальня', icon: '🍽️', level: 'B1', words: 10 },
      { title: 'Кухня', icon: '🍳', level: 'A2', words: 12 },
      { title: 'Кухонне приладдя', icon: '🔪', level: 'A2', words: 22 },
      { title: 'Приготування їжі', icon: '🥘', level: 'B1', words: 16 },
      { title: 'Спальня', icon: '🛏️', level: 'A2', words: 11 },
      { title: 'Ванна кімната', icon: '🛁', level: 'A2', words: 13 },
      { title: 'Будинок', icon: '🏡', level: 'A1', words: 10 },
      { title: 'Електрика', icon: '⚡', level: 'B2', words: 8 },
      { title: 'Сантехніка', icon: '🚰', level: 'B2', words: 2 },
      { title: 'Хатні справи', icon: '🧹', level: 'B1', words: 13 },
      { title: 'Ремонт', icon: '🛠️', level: 'B2', words: 9 },
      { title: 'Інструменти', icon: '🪛', level: 'B2', words: 9 },
      { title: 'Оздоблення', icon: '🎨', level: 'B2', words: 10 },
      { title: 'Рослини', icon: '🪴', level: 'B1', words: 19 },
      { title: 'Садівництво', icon: '🧑‍🌾', level: 'B2', words: 10 },
      { title: 'Садові інструменти', icon: '🪣', level: 'B2', words: 7 },
      { title: 'Сад', icon: '🌲', level: 'B1', words: 9 },
    ]
  },
  {
    id: 'city_life',
    title: 'Міське життя',
    icon: '🏙️',
    level: 'A2',
    totalWords: 120,
    subcategories: [
      { title: 'У місті', icon: '🌆', level: 'A2', words: 25 },
      { title: 'Будівлі та архітектура', icon: '🏢', level: 'B2', words: 8 },
      { title: 'Банк', icon: '🏦', level: 'B1', words: 8 },
      { title: 'Пошта', icon: '📮', level: 'B1', words: 8 },
      { title: 'Покупки', icon: '🛍️', level: 'A2', words: 8 },
      { title: 'Торговий центр', icon: '🏬', level: 'B1', words: 11 },
      { title: 'Супермаркет', icon: '🛒', level: 'B1', words: 13 },
      { title: 'Аптека', icon: '💊', level: 'B1', words: 12 },
      { title: 'Екстрені служби', icon: '🚓', level: 'B1', words: 20 },
      { title: 'Енергія', icon: '🔋', level: 'B2', words: 7 },
    ]
  },
  {
    id: 'food',
    title: 'Їжа',
    icon: '🍔',
    level: 'A1',
    totalWords: 228,
    subcategories: [
      { title: 'Напої', icon: '🥤', level: 'A1', words: 16 },
      { title: 'Їжа', icon: '🍽️', level: 'A1', words: 16 },
      { title: 'М\'ясо', icon: '🥩', level: 'A2', words: 21 },
      { title: 'Риба', icon: '🐟', level: 'B1', words: 20 },
      { title: 'Овочі', icon: '🥕', level: 'A2', words: 24 },
      { title: 'Фрукти', icon: '🍎', level: 'A2', words: 30 },
      { title: 'Горіхи', icon: '🥜', level: 'B1', words: 5 },
      { title: 'Спеції', icon: '🌶️', level: 'B2', words: 13 },
      { title: 'Комора', icon: '🥫', level: 'B1', words: 11 },
      { title: 'Молочні продукти', icon: '🥛', level: 'A2', words: 9 },
      { title: 'Пекарня', icon: '🥖', level: 'B1', words: 14 },
      { title: 'Гастроном', icon: '🧀', level: 'B2', words: 4 },
      { title: 'У кафе', icon: '☕', level: 'A2', words: 12 },
      { title: 'Солодощі', icon: '🍬', level: 'B1', words: 4 },
      { title: 'У барі', icon: '🍻', level: 'B1', words: 4 },
      { title: 'У ресторані', icon: '🍽️', level: 'A2', words: 11 },
      { title: 'Фастфуд', icon: '🍟', level: 'B1', words: 5 },
      { title: 'Сніданок', icon: '🥞', level: 'A1', words: 5 },
      { title: 'Прийом їжі', icon: '🍲', level: 'A1', words: 4 },
    ]
  },
  {
    id: 'education',
    title: 'Навчання',
    icon: '🎓',
    level: 'A2',
    totalWords: 176,
    subcategories: [
      { title: 'Школа', icon: '🏫', level: 'A2', words: 50 },
      { title: 'Математика', icon: '➗', level: 'B1', words: 32 },
      { title: 'Фізика', icon: '🧲', level: 'B2', words: 10 },
      { title: 'Хімія', icon: '🧪', level: 'B2', words: 15 },
      { title: 'Біологія', icon: '🧬', level: 'B2', words: 19 },
      { title: 'Історія', icon: '📜', level: 'B1', words: 31 },
      { title: 'Виш', icon: '🏛️', level: 'B1', words: 19 },
    ]
  },
  {
    id: 'work',
    title: 'Робота',
    icon: '💼',
    level: 'A2',
    totalWords: 209,
    subcategories: [
      { title: 'На роботі', icon: '🏢', level: 'B1', words: 23 },
      { title: 'В офісі', icon: '📠', level: 'B1', words: 15 },
      { title: 'Комп\'ютери', icon: '💻', level: 'B1', words: 18 },
      { title: 'ЗМІ', icon: '📰', level: 'B2', words: 14 },
      { title: 'Право', icon: '⚖️', level: 'B2', words: 25 },
      { title: 'Сільське господарство', icon: '🚜', level: 'B2', words: 18 },
      { title: 'Будівництво', icon: '🏗️', level: 'B2', words: 10 },
      { title: 'Військо', icon: '🪖', level: 'B2', words: 11 },
      { title: 'Професії', icon: '🧑‍🏭', level: 'A2', words: 28 },
      { title: 'Галузі', icon: '🏭', level: 'B2', words: 22 },
      { title: 'Пошук роботи', icon: '📄', level: 'B1', words: 3 },
      { title: 'Навички', icon: '🎯', level: 'B1', words: 10 },
      { title: 'Фінанси', icon: '💰', level: 'B1', words: 9 },
      { title: 'Нарада', icon: '🤝', level: 'B1', words: 3 },
    ]
  },
  {
    id: 'transport',
    title: 'Пересування',
    icon: '🚗',
    level: 'A2',
    totalWords: 98,
    subcategories: [
      { title: 'Дороги', icon: '🛣️', level: 'B1', words: 8 },
      { title: 'Автомобілі', icon: '🚙', level: 'A2', words: 20 },
      { title: 'Автобуси', icon: '🚌', level: 'A2', words: 7 },
      { title: 'Мотоцикли', icon: '🏍️', level: 'B2', words: 3 },
      { title: 'Велоспорт', icon: '🚲', level: 'B1', words: 10 },
      { title: 'Потяги', icon: '🚂', level: 'A2', words: 8 },
      { title: 'Літаки', icon: '✈️', level: 'B2', words: 7 },
      { title: 'В аеропорту', icon: '🛂', level: 'A2', words: 14 },
      { title: 'Судна', icon: '🚢', level: 'B2', words: 10 },
      { title: 'Порт', icon: '⚓', level: 'B2', words: 11 },
    ]
  },
  {
    id: 'sports',
    title: 'Спорт',
    icon: '⚽',
    level: 'B1',
    totalWords: 112,
    subcategories: [
      { title: 'Американський футбол', icon: '🏈', level: 'B2', words: 9 },
      { title: 'Футбол', icon: '⚽', level: 'B1', words: 7 },
      { title: 'Хокей і лакрос', icon: '🏒', level: 'B2', words: 3 },
      { title: 'Баскетбол', icon: '🏀', level: 'B2', words: 7 },
      { title: 'Бейсбол', icon: '⚾', level: 'B2', words: 5 },
      { title: 'Теніс', icon: '🎾', level: 'B1', words: 14 },
      { title: 'Гольф', icon: '⛳', level: 'B2', words: 6 },
      { title: 'Легка атлетика', icon: '🏃', level: 'B1', words: 6 },
      { title: 'Бойові види спорту', icon: '🥊', level: 'B2', words: 6 },
      { title: 'Плавання', icon: '🏊', level: 'B1', words: 4 },
      { title: 'Водні види спорту', icon: '🏄', level: 'B2', words: 2 },
      { title: 'Верхова їзда', icon: '🏇', level: 'B2', words: 7 },
      { title: 'Риболовля', icon: '🎣', level: 'B2', words: 9 },
      { title: 'Зимові види спорту', icon: '🎿', level: 'B2', words: 5 },
      { title: 'Мотоспорт', icon: '🏎️', level: 'B2', words: 1 },
      { title: 'Спортзал', icon: '🏋️', level: 'B1', words: 11 },
      { title: 'Інші види спорту', icon: '🎯', level: 'B1', words: 10 },
    ]
  },
  {
    id: 'leisure',
    title: 'Дозвілля',
    icon: '🎮',
    level: 'A2',
    totalWords: 193,
    subcategories: [
      { title: 'На сцені', icon: '🎭', level: 'B2', words: 17 },
      { title: 'Фільми', icon: '🍿', level: 'B1', words: 14 },
      { title: 'Музика', icon: '🎸', level: 'B1', words: 27 },
      { title: 'Музеї', icon: '🖼️', level: 'B2', words: 8 },
      { title: 'Подорожі', icon: '🧳', level: 'A2', words: 5 },
      { title: 'Огляд визначних місць', icon: '🗺️', level: 'B1', words: 7 },
      { title: 'Активний відпочинок', icon: '🧗', level: 'B1', words: 8 },
      { title: 'Пляж', icon: '🏖️', level: 'B1', words: 8 },
      { title: 'Кемпінг', icon: '⛺', level: 'B1', words: 9 },
      { title: 'Домашні розваги', icon: '🧩', level: 'B2', words: 8 },
      { title: 'Телебачення', icon: '📺', level: 'B1', words: 17 },
      { title: 'Книги', icon: '📚', level: 'B1', words: 23 },
      { title: 'Фентезі', icon: '🧙', level: 'B2', words: 24 },
      { title: 'Ігри', icon: '🎲', level: 'B1', words: 18 },
    ]
  },
  {
    id: 'environment',
    title: 'Довкілля',
    icon: '🌍',
    level: 'A1',
    totalWords: 129,
    subcategories: [
      { title: 'Космос', icon: '🚀', level: 'B2', words: 37 },
      { title: 'Земля', icon: '🌏', level: 'B2', words: 13 },
      { title: 'Географія', icon: '🗺️', level: 'B1', words: 35 },
      { title: 'Напрямки', icon: '🧭', level: 'A2', words: 13 },
      { title: 'Погода', icon: '☀️', level: 'A1', words: 28 },
      { title: 'Клімат', icon: '🌡️', level: 'B1', words: 3 },
    ]
  },
  {
    id: 'nature',
    title: 'Природа',
    icon: '🌲',
    level: 'A1',
    totalWords: 165,
    subcategories: [
      { title: 'Ссавці', icon: '🐻', level: 'B1', words: 36 },
      { title: 'Птахи', icon: '🦅', level: 'B1', words: 24 },
      { title: 'Комахи', icon: '🦋', level: 'B1', words: 24 },
      { title: 'Плазуни', icon: '🦎', level: 'B2', words: 9 },
      { title: 'Домашні улюбленці', icon: '🐕', level: 'A1', words: 16 },
      { title: 'Свійські тварини', icon: '🐄', level: 'A2', words: 23 },
      { title: 'Життя океану', icon: '🐋', level: 'B1', words: 12 },
      { title: 'Рослини та дерева', icon: '🌿', level: 'B1', words: 21 },
    ]
  },
  {
    id: 'reference',
    title: 'Довідник',
    icon: '📖',
    level: 'A1',
    totalWords: 226,
    subcategories: [
      { title: 'Час', icon: '⏳', level: 'A1', words: 16 },
      { title: 'Календар', icon: '📅', level: 'A1', words: 33 },
      { title: 'Числа', icon: '🔢', level: 'A1', words: 40 },
      { title: 'Міри та ваги', icon: '⚖️', level: 'A2', words: 12 },
      { title: 'Письмо', icon: '✍️', level: 'B1', words: 15 },
      { title: 'Матеріали', icon: '🧱', level: 'B1', words: 17 },
      { title: 'Описи', icon: '📝', level: 'A1', words: 33 },
      { title: 'Думки', icon: '💭', level: 'B1', words: 25 },
      { title: 'Поширені дієслова', icon: '🏃', level: 'B1', words: 12 },
      { title: 'Корисні вирази', icon: '💬', level: 'A1', words: 23 },
    ]
  }
];